# Generated by Django 5.2 on 2025-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookentry",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
