# Generated by Django 5.2 on 2025-04-24 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbook", "0002_guestbookentry_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestbookentry",
            options={"verbose_name": "방명록", "verbose_name_plural": "방명록"},
        ),
        migrations.RemoveField(
            model_name="guestbookentry",
            name="name",
        ),
        migrations.AddField(
            model_name="guestbookentry",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
        migrations.AddField(
            model_name="guestbookentry",
            name="title",
            field=models.CharField(
                default="admin", max_length=200, verbose_name="제목"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="guestbookentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="guestbookentry",
            name="message",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="guestbookentry",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
