# Generated by Django 5.2 on 2025-04-25 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gbook", "0003_alter_guestbookentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestbookentry",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/", verbose_name="첨부파일"
            ),
        ),
        migrations.CreateModel(
            name="GuestBookFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="gbook.guestbookentry",
                    ),
                ),
            ],
        ),
    ]
