# Generated by Django 5.2 on 2025-04-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gbook", "0004_guestbookentry_file_guestbookfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guestbookfile",
            options={"verbose_name": "첨부파일", "verbose_name_plural": "첨부파일"},
        ),
        migrations.RemoveField(
            model_name="guestbookentry",
            name="file",
        ),
    ]
