# Generated by Django 5.2 on 2025-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "주문완료"), ("cancelled", "취소됨")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
